//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cadastral.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Immovable
    {
        public int ImmovableId { get; set; }
        public int ImmovableTypeId { get; set; }
        public string Address { get; set; }
        public int OwnerId { get; set; }
        public decimal Cost { get; set; }
        public int CadastrId { get; set; }
    
        public virtual ImmovableType ImmovableType { get; set; }
        public virtual Owner Owner { get; set; }
        public virtual Cadastr Cadastr { get; set; }
    }
}
