//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cadastral.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class LicenseRequest
    {
        public int LicenseId { get; set; }
        public int CadastrId { get; set; }
    
        public virtual Cadastr Cadastr { get; set; }
    }
}
